## DS Fund Unit 2 Lesson 1 Section 1

In [70]:
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET

In [4]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [8]:
w = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
x = np.array([0, 1, 2, 3])

# Square each value.
print(np.square(x))

# Square root of each value.
print(np.sqrt(x))

# Cosine of each value.
print(np.cos(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [16]:
x = np.array([0, 1, 2, 3])

# Find the maximum value.
print(np.max(x))

# Find the minimum value.
print(np.min(x))

# Find the mean of the input array.
print(np.mean(x))

# Find the standard deviation of the input array.
print(np.std(x))

3
0
1.5
1.118033988749895


## DS Fund Unit 2 Lesson 1 Section 2

In [18]:
my_array = np.array([['Montgomery','Yellohammer state',52423],
                     ['Sacramento','Golden state',163707],
                     ['Oklahoma City','Sooner state',69960 ]])
df = pd.DataFrame(my_array)
df

0                  1       2
0     Montgomery  Yellohammer state   52423
1     Sacramento       Golden state  163707
2  Oklahoma City       Sooner state   69960

In [20]:
df.columns = ['Capital', 'Nickname','Area']
df.index = ['Alabama', 'California', 'Oklahoma']
df

Capital           Nickname    Area
Alabama        Montgomery  Yellohammer state   52423
California     Sacramento       Golden state  163707
Oklahoma    Oklahoma City       Sooner state   69960

In [22]:
df2 = pd.DataFrame(
    my_array,
    columns=['Capital', 'Nickname','Area'],
    index=['Alabama', 'California', 'Oklahoma'])
df2

Capital           Nickname    Area
Alabama        Montgomery  Yellohammer state   52423
California     Sacramento       Golden state  163707
Oklahoma    Oklahoma City       Sooner state   69960

In [24]:
# This list will become our row names.
names = ['George',
         'John',
         'Thomas',
         'James',
         'Andrew',
         'Martin',
         'William',
         'Zachary',
         'Millard',
         'Franklin']

# Create an empty data frame with named rows.
purchases = pd.DataFrame(index=names)

# Add our columns to the data frame one at a time.
purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases 

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [26]:
purchases['items_purch_per_ad'] = purchases['items_purchased'] / purchases['ad_views']
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        42                1            0.023810
Thomas       CAN        32                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        63                0            0.000000
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Millard      CAN        16                0            0.000000
Franklin      US        77                5            0.064935

In [28]:
purchases['items_purchased'] / purchases['ad_views']

George      0.125000
John        0.023810
Thomas      0.000000
James       0.615385
Andrew      0.000000
Martin      0.263158
William     0.107692
Zachary     0.130435
Millard     0.000000
Franklin    0.064935
dtype: float64

## DS Fund Unit 2 Lesson 1 Section 3

In [31]:

# Reload example data from last assignment. 
names = ['George',
         'John',
         'Thomas',
         'James',
         'Andrew',
         'Martin',
         'William',
         'Zachary',
         'Millard',
         'Franklin']
purchases = pd.DataFrame(index=names)
purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]

In [33]:
purchases['country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [35]:
purchases.loc['George']


country            US
ad_views           16
items_purchased     2
Name: George, dtype: object

In [37]:
purchases.loc[:, 'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [39]:
purchases.loc['George', 'country']

'US'

In [42]:
purchases.iloc[1:3, 1]

John      42
Thomas    32
Name: ad_views, dtype: int64

In [47]:
purchases.loc[lambda df: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased
George        US        16                2
James         US        13                8
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Franklin      US        77                5

In [49]:
purchases[purchases['items_purchased'] > 1]

country  ad_views  items_purchased
George        US        16                2
James         US        13                8
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Franklin      US        77                5

In [51]:
purchases.groupby('country')

In [53]:
grouped = purchases.groupby('country')
grouped.groups

{'CAN': Index(['John', 'Thomas', 'Andrew', 'Millard'], dtype='object'),
 'US': Index(['George', 'James', 'Martin', 'William', 'Zachary', 'Franklin'], dtype='object')}

In [55]:
purchases.groupby('country').aggregate(np.mean)

# Don't want to take the mean of all columns? Try this:
# purchases.groupby('country')['column_name'].mean()

ad_views  items_purchased
country                           
CAN         38.25             0.25
US          35.50             5.00

In [60]:
purchases.groupby('country')['ad_views'].sum()

country
CAN    153
US     213
Name: ad_views, dtype: int64

## DS Fund Unit 2 Lesson 1 Section 4

In [63]:
df = pd.read_csv('purchases.csv')
df

Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5

In [65]:
df.to_csv('my_purchases.csv')

In [67]:
df = pd.read_json('purchases.json')
df

Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5

In [69]:
df.to_json('my_purchases_json_file.json')

In [74]:
# Load and parse the XML file into a tree.
tree = ET.parse('purchases.xml')

# Find the root of the tree. This is the node of the tree where we'll
# start our iteration.
root = tree.getroot()

# Define a custom function to loop over our tree, extract values, and
# return a two-dimensional list.
def xml_to_list(root):
    result = []
    for row in root:
        row_list = []
        for column in row:
            row_list.append(column.text)
        result.append(row_list)
    return result
    
# Feed our two-dimensional list into Pandas.
df = pd.DataFrame(xml_to_list(root))
print(df)

          0    1   2  3
0    George   US  16  2
1      John  CAN  42  1
2    Thomas  CAN  32  0
3     James   US  13  8
4    Andrew  CAN  63  0
5    Martin   US  19  5
6   William   US  65  7
7   Zachary   US  23  3
8   Millard  CAN  16  0
9  Franklin   US  77  5


In [76]:
# Let's open the poem.txt file, create a file object, and print out the
# file text line by line.
# Note the poem.txt tab above.
with open('poem.txt') as poem_file:
    text = poem_file.readlines()
    print("This file is {} lines long\n".format(len(text)))
    for line in text:
        print(line)

# Try loading and printing the purchases.csv file line by line just
# just like we did for poem.txt.

This file is 19 lines long

Beautiful is better than ugly.

Explicit is better than implicit.

Simple is better than complex.

Complex is better than complicated.

Flat is better than nested.

Sparse is better than dense.

Readability counts.

Special cases aren't special enough to break the rules.

Although practicality beats purity.

Errors should never pass silently.

Unless explicitly silenced.

In the face of ambiguity, refuse the temptation to guess.

There should be one-- and preferably only one --obvious way to do it.

Although that way may not be obvious at first unless you're Dutch.

Now is better than never.

Although never is often better than *right* now.

If the implementation is hard to explain, it's a bad idea.

If the implementation is easy to explain, it may be a good idea.

Namespaces are one honking great idea -- let's do more of those!
